services:
  web:
    image: roe
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    volumes:
      - .:/home/node/app
  mongodb:
    image: mongo
    ports:
      - 27017:27016
    volumes:
      - data:/data/db

volumes:
  data:
